### ISSUE TITLE
Jar Doesn't Run in MDK and no deob jar provided

### ISSUE THREAD

**Issue by jredfox** [jellysquid3/Phosphor#17]
Jar Doesn't Run in MDK and no deob jar provided.
StackTrace:
https://pastebin.com/HG9VLEEG

then later since the asm fails it crashes

**Comment by jellysquid3** [comment]
Deobfuscated JARs are provided on the [Maven](https://repo.gildedgames.com/maven/me/jellysquid/mods/phosphor/) and [Jenkins](https://jenkins.gildedgames.com/blue/organizations/jenkins/Phosphor/activity) with the `dev` classifier. It is expected that developers using Phosphor in de-obfuscated environments use the Maven instead of downloading the mod from Curseforge.

**Comment by jredfox** [comment]
curseforge has a builtin feature to upload deob jars specifically for this purpose please on stable builds push a deob jar to this

**Comment by jellysquid3** [comment]
I am not making plans to upload de-obfuscated builds to Curseforge. The Maven is very easy to configure in your build script and is superior to downloading and manually installing JARs from Curseforge.
