### ISSUE TITLE
[BUG] Crash alongside Spongeforge

### ISSUE THREAD

**Issue by T145** [jellysquid3/Phosphor#18]
Literally just the two mods and nothing else causes bad things to happen.

https://paste.ee/p/FgOoG

And yes, I tested it on the Spongeforge recommended Forge version to the same result. Noticed #12 so hopefully this will be a non-issue. Have you looked into alternative open libraries, like LLibrary, so you don't have to write your own ASM stuff?

**Comment by jellysquid3** [comment]
LLibrary contains quite a bit more than ASM utilities, and is a bit too over-reaching for me to consider having Phosphor depend on it.

As for the issue here, the conflict is not caused by SpongeForge, but rather LiteLoader shipping an old version of Sponge Mixins. Given that LiteLoader does not seem to be maintained anymore (last build was a year and a half ago) and that we can't depend on an earlier version of Sponge Mixins (we use the latest features), I'm afraid you're stuck choosing between either using LiteLoader or Phosphor for the time being.

In a future release, #12 will move us away from Sponge Mixins and this will no longer be a problem, but work is still needed on that front and I found my time a bit limited this past week.

**Comment by jellysquid3** [comment]
It's also worth pointing out that LiteLoader is client-side only, and Phosphor can be installed on the server without requiring clients to also have the mod installed (though you'll only see improved performance on the server-side.)
