### ISSUE TITLE
Lighting issues when loading new chunks. 

### ISSUE THREAD

**Issue by Glamdring804** [jellysquid3/Phosphor#25]
I have these awful lighting problems when I try to generate new chunks with Phosphor installed. 

https://i.imgur.com/WZFMU97.png

The darkened blocks appear to have some sort of invisible pseudo-block on top of them, that slows your movement and makes it all jittery when you try to move through it (like the phantom blocks that are sometimes created by mining too fast). Placing any placable item in one of the darkened blocks instead results in a black-pink untextured block. Breaking that untextured block fixes the lighting issue for that block and that block only. 

If it's relevant, you can view the rest of my modlist here. Maybe the issue is an incompatibility.

https://www.reddit.com/r/FeedTheBeastCrashes/comments/c0b57i/lighting_errors_while_generating_new_chunks_in_a/

**Comment by jellysquid3** [comment]
Unfortunately, it is virtually impossible for me to debug issues like this when 100+ mods are present and there is no additional information. I won't be able to figure out what's breaking here until the conflicting mods are narrowed down. 

In your log file, there is mention of `MineshotCore` which is not being loaded because it is only compatible with Minecraft 1.12. Seeing as how an incompatible version somehow managed to get into your mods folder, it is possible that other incompatible coremods were installed and Forge is letting them run because they do not specify their required version and in turn, possibly mangling the game. I would strongly recommend that you begin by upgrading your mods to their latest versions first (especially Forge and Optifine), and verify that you are using mods compatible with Minecraft 1.12.2.

If the issue persists, please work through your list of _coremods_ (which are most likely to conflict with Phosphor) and remove them one by one to figure out if any of them affect the issue.

**Comment by Glamdring804** [comment]
I understand, and I'm sorry I wasn't able to provide more information. I won't have the chance to do more in-depth testing for a couple weeks. Once I do, I'll update you with my results. Until then, I'm just going to have to run without phosphor for now. Thank you for your time, and for the effort you've put into making this mod.

**Comment by jellysquid3** [comment]
I appreciate the report nevertheless. It may provide useful data in the future. I will close this issue for the time being. In the future when more information is available, please don't hesitate to re-open this issue.
