### ISSUE TITLE
Incompatibilities with VanillaFix and LagGoggles

### ISSUE THREAD

**Issue by big-lip-bob** [jellysquid3/Phosphor#27]
Since i put in Phosphor my game doesn't want to launch and complain about mixins
https://hastebin.com/imenimabun.sql whenever i remove one of those mods, an other mod gets blamed

**Comment by big-lip-bob** [comment]
https://hastebin.com/ofibuqamuv.sql
https://hastebin.com/evitiqeqoj.sql

**Comment by jellysquid3** [comment]
Please upload a complete client debugging log.

**Comment by big-lip-bob** [comment]
https://hastebin.com/eripavugof.md here, with the 3 mods included, i tried to reinstall forge but out of luck i can list my mods aswell

**Comment by big-lip-bob** [comment]
https://hastebin.com/qakugayifi.css

**Comment by big-lip-bob** [comment]
Minecraft just hangs up, does not crash but does not pop up aswell, just sits dead in background

**Comment by jellysquid3** [comment]
This looks to be a problem with another mod which is loading the `World` class during the coremod initialization stage, and Mixins itself is reporting the issue. Phosphor is not responsible for any error here. You likely introduced another change when including Phosphor into your game which has caused this breakage.

```
Advanced Macros
Bloodmoon
Colytra
CreativeCore
Connected Textures Mod
Foamfix
Hammercore
Inventory Tweaks
LittleTiles
OpenComputers
OpenSecurity
p455w0rd's Library
Quark
RandomPatches
SereneSeasons
SmoothFont
EnderCore
VanillaFix
```
Please examine this list of coremods you have installed and remove any recent additions one-by-one, and if that fails, remove all of them (including dependent mods) one-by-one until the problem is resolved. Once you have found the problem mod, report it to their respective issue tracker. There is nothing else I can do about this issue.

**Comment by big-lip-bob** [comment]
okay thanks,i will see what i can do

**Comment by big-lip-bob** [comment]
It was indeed not your fault but P4ssW0rd's and he fixed the bug, ive contacted him so now everything is fine, thanks for your help and keep Phoshor up

**Comment by jellysquid3** [comment]
For future stumblers on this issue, please update p455w0rd's Library to 1.12.2-2.2.150 or newer.
