### ISSUE TITLE
Phosphor is incompatible with SpongeForge RC3844 and newer 

### ISSUE THREAD

**Issue by LemADEC** [jellysquid3/Phosphor#34]
As of 1.12.2-0.2.4+build46, game won't boot with SpongeForge RC3847.
Issue isn't reproduced with SpongeForge RC3843, something probably broke in between as Sponge is going through lots of class renaming.

https://gist.github.com/LemADEC/6760a2b466356f61f0b269f8f6ddf762

**Comment by bluelightning32** [comment]
I hit this also with SpongeForge RC3848.

**Comment by bluelightning32** [comment]
Does not affect RC3822.

**Comment by bluelightning32** [comment]
Does not affect RC3835.

**Comment by LemADEC** [comment]
As initially posted, it comes from Sponge changing their internal classes between RC3843 and RC3847. Try the versions in between those 2.

**Comment by SamuelWAnderson45** [comment]
RC3844 is the version that broke it.
The commit that caused it is https://github.com/SpongePowered/SpongeForge/commit/306b3cac86a13cef1eaa7cc95e3f2507d9feeb13
According to SpongeForge, Phosphor needs to update [https://github.com/SpongePowered/SpongeForge/issues/2871#issuecomment-511241276](https://github.com/SpongePowered/SpongeForge/issues/2871#issuecomment-511241276)

**Comment by jellysquid3** [comment]
Sorry for the late response. This is an issue with Phosphor, not SpongeForge. We patch the internal implementation of Sponge's wrapper for `Chunk#setBlockState`. It seems they've changed some things internally. For the time being, you'll simply need to use an older version of SpongeForge (something before RC3844, as stated above.) My hesitance to resolve this earlier was due to my work on eventually replacing Mixins in Phosphor. 

I will update the Mixins branch of Phosphor tomorrow to account for these changes. I'm hopeful the extent is purely just a method name change. If so, it should be possible to get a new release out pretty quickly that will retain compatibility with older releases of SpongeForge as well.

**Comment by MaxIsH0t** [comment]
Can you please fix this??

**Comment by SamuelWAnderson45** [comment]
@MaxIsH0t just downgrade to RC3843 for now. And be patient.

**Comment by jellysquid3** [comment]
There are additional changes other than just the method names that Phosphor needs to accommodate, it seems.  :slightly_frowning_face: 

It won't be as easy of an update as I thought to bring things back up to speed with SpongeForge. It's being worked on with what free time I can spare, though.

**Comment by jellysquid3** [comment]
Sorry for all the additional delay. [I've released Phosphor 0.2.5 which resolves this issue.](https://www.curseforge.com/minecraft/mc-mods/phosphor/files/2745940)
