### ISSUE TITLE
Project Ozone 3 - Another mod has attempted to modify the world's state

### ISSUE THREAD

**Issue by soulless10** [jellysquid3/Phosphor#38]
Error here: https://pastebin.com/2hmKscER
Started after I got a portal to Landia and got tinker shuriken with portly gentlemen and global traveler, maybe related?

EDIT: Only get error when shooting tinkers shuriken with a enderium knife blade - thinking it's to do with tinkers now

**Comment by jellysquid3** [comment]
It appears that another mod is spawning particles on the client with the server world (which is a violation of Minecraft's sided contract). Can you please upload a full client debug log file?

**Comment by soulless10** [comment]
I cannot find the file you have mentioned (I'm running the modpack from the Twitch launcher if that changes anything)

**Comment by jellysquid3** [comment]
The log file can be found titled `debug.log` in the `logs` folder within your modpack's game data folder. However, that said, this issue is very likely the result of another mod spawning a particle on the client with the server's world. If that is the case, there will be little I can do about the problem.
