### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Crosus97** [jellysquid3/Phosphor#42]
i need help,  dont know what to do, i have my server with 6 persons, and when 1 explore, the server has massive lag, i install this mod, but i dont detect anything

i have any incompatiblity mod or something? maybe you can helpme in a good execution line

the machine dedicated is ,32GB RAM, SSD, Ryzen 7 2700x

and the server said causiing cascading lag world gen
im configuring bad you mod? i need to do anything?

**Comment by Crosus97** [comment]
thanks for the future response

**Comment by Crosus97** [comment]
can you saidme a goo execution line for Java .bat maybe?

**Comment by jellysquid3** [comment]
Phosphor only targets the lighting engine and will not do anything for misbehaving mods which generate structures outside their chunk (i.e. Recurrent Complex.)  Cascading chunk generation can lead to extremely long tick times which are caused by terrain and structure generation, not lighting propagation. You should look into your log files or server console to identify the mod which is resulting in cascading chunk generation and take steps to correct it with that mod.
