### ISSUE TITLE
Phosphor Prevents Startup

### ISSUE THREAD

**Issue by KentaigaIBE** [jellysquid3/Phosphor#44]
MC Version: 1.12.2
Forge Version: 14.23.5.2847
Phosphor version: 2.3+
---------------------------------------
This has been a recurring problem ever since Phosphor version 2.3 for me, the update that added forced Mixin version compliance. It completely prevents startup, so much so that there's no crash log. The packaged Mixin version is claiming to be 0.7.5 when it requires 0.7.10. I tried to upgrade the version myself, but I don't have the technical know-how to do so, it seems. Perhaps you have a solution for me. I could be overlooking something really simple here so excuse me if this is a simple fix.

Of note: this also affects every version of the Aether II mod that has Phosphor 2.3+ bundled. It's the exact same error in the log, so I assume it's no coincidence.

Here is the standard log of the latest run: [latest.log](https://github.com/jellysquid3/Phosphor/files/3640406/latest.log)

**Comment by creepinson** [comment]
Same issue

**Comment by jellysquid3** [comment]
LiteLoader is incompatible with Phosphor and many other mods due to it bundling a much older version of Sponge Mixins. The only solution to the issue is to remove LiteLoader from your game given they have not released a new build in 2 years. Unfortunately, there is nothing else that can be done from my side.
