### ISSUE TITLE
Support for Minecraft 1.14.4

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Phosphor#52]
Edit: Initial builds for Fabric [are now available on my Patreon.](https://www.patreon.com/jellysquid) I've also made a post on my Patreon page describing the plans and rationale for making these builds supporter-only. [You can find it over here.](https://www.patreon.com/posts/announcing-for-1-31729623)

----

This is a tracking issue for adding support for Minecraft 1.14.4 to Phosphor. This version of the mod has required a complete rewrite from the ground up, but progress is now moving forward rapidly!

The current plan is to maintain two source code branches, one for Fabric and Forge. Both platforms will be treated as first-class citizens and will receive updates together.

The initial builds of Phosphor for Minecraft 1.14.4 will be available [exclusively to my supporters on Patreon](https://www.patreon.com/jellysquid) for a short period. I believe this is the best approach for allowing users to get their hands on early rudimentary versions of Phosphor while also giving them the ability to help buy me food and support development.

The source code will as always remain public under a free and open source license, and users who are wishing to hack on the code can compile builds from source which will be identical to these builds.

- [x] Finish an minimal viable product in Fabric 
- [x] Create a port of the MVP to Forge
- [x] Begin producing builds for both Fabric and Forge, make them available to my supporters on Patreon
- [x] Look for additional optimization opportunities and fix bugs as they come up in the early builds
- [x] Promote a build to stable status and upload to Curseforge

**Comment by jellysquid3** [comment]
The source code for the Fabric variant is already available on the [1.14.x/fabric branch](https://github.com/jellysquid3/Phosphor/tree/1.14.x/fabric).

**Comment by jellysquid3** [comment]
We now also have a branch for Forge available on the [1.14.x/forge branch](https://github.com/jellysquid3/Phosphor/tree/1.14.x/forge), but it does not work out of the box for users.

You'll need to add the [`org.ow2.asm:asm-util:6.2`](https://search.maven.org/artifact/org.ow2.asm/asm-util/6.2/jar) and [`org.spongepowered:mixin:0.8-SNAPSHOT`](http://jenkins.liteloader.com/job/Mixin/275/) libraries to your game's classpath by modifying the version manifest for your installation and dropping it into your launcher's appropriate `libraries` folder.

**Comment by jellysquid3** [comment]
Initial builds for Fabric [are now available on my Patreon.](https://www.patreon.com/jellysquid) I've also made a post on my Patreon page describing the plans and rationale for making these builds supporter-only. [You can find it over here.](https://www.patreon.com/posts/announcing-for-1-31729623)

**Comment by liach** [comment]
Mind consider a port to 1.15 pre releases (fabric)? afaik the worldgen engine did not change drastically in 1.15 update, and a port to pre release is most likely be usable on releases without any tweak.

**Comment by jellysquid3** [comment]
@liach It's not out of the question, though truthfully I would prefer to keep releases of Phosphor to stable releases of Minecraft as it reduces maintenance burden.

**Comment by grondag** [comment]
Hi, I'm the author of the [Canvas renderer](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer) for Fabric and I am interested in making significant changes to the lighting engine also. Some of those changes would probably overlap significantly with work you have already done. Some would not but might benefit from that work even so.  More detail on my vague plans is here: https://github.com/grondag/canvas/wiki/Canvas-Feature-Roadmap#v08-better-lighting

As you know, this is a lot of work and I don't want to duplicate efforts. At the same time, I prefer to keep Canvas licensed as Apache instead of GPL.  I'd be happy to make this a collaboration if we can come to some agreement in that regard.  Let me know if you have any interest. 

Otherwise I will avoid looking at your code and muddle through on my own.  Either way, I applaud your efforts and appreciate you for making this open source.

**Comment by jellysquid3** [comment]
Phosphor 0.3.3 will be landing on Curseforge for Minecraft 1.14.4 and 1.15.1 today with some big improvements. :smile:

![Time spent lighting chunks](https://user-images.githubusercontent.com/1363084/71130928-1a454580-21eb-11ea-86e6-bbb973a520e2.png)

**Comment by jellysquid3** [comment]
[We're now live on CurseForge.](https://www.curseforge.com/minecraft/mc-mods/phosphor) Thanks to everyone who helped development along and to my supporters on Patreon.

**Comment by thegamerx1** [comment]
Forge?

**Comment by Zoutelande** [comment]
> Forge?

https://github.com/jellysquid3/Phosphor/issues/52#issuecomment-558884482

**Comment by lamoyrl90** [comment]
Any chance this might backtrack to Forge MC 1.14.4? I'm still using that one because IE and Create haven't made their way to 1.15.2 yet, but 1.14.4 still has an irritating stutter that I'm pretty sure stems from MC's lighting algorithms. Optifine is out of the question since I believe their focus is on porting to 1.15.2, and their latest release for 1.14.4 is only compatible with a couple versions of forge which IE doesn't support.

**Comment by jellysquid3** [comment]
There are issues with Forge in Minecraft 1.14 which prevent Mixins from working correctly without modifying libraries on the classpath, which is why there hasn't been a formal release of Phosphor for it. It's my understanding this situation will not change, and as such is why my mods only support Forge for Minecraft 1.15.

**Comment by lamoyrl90** [comment]
Oh, I see now. I thought maybe you found a way to make it work, I didn't realize 1.15 was just more compatible.
