### ISSUE TITLE
Server crash with EvilCraft (getLightValue)

### ISSUE THREAD

**Issue by SSKirillSS** [jellysquid3/Phosphor#7]
spongeforge-1.12.2-2768-7.1.6-RC3665
EvilCraft-1.12.2-0.10.72
CyclopsCore-1.12.2-1.1.1
phosphor-1.12.2-0.2.2+build43-universal

async-lighting turned false

Crash-report - https://pastebin.com/u5QKhrPm

**Comment by jellysquid3** [comment]
This looks as if EvilCraft is not checking whether or not their tile entity properly exists in the world before trying to interact with it. Modders should always make sure that the tile entity returned by `World#getTileEntity` is of the right type _before_ casting it.

I will look into sending a PR to their project when I have the time.

**Comment by EightBlade** [comment]
I'm having a similar issue. https://pastebin.com/89iNfb4z

**Comment by jellysquid3** [comment]
I'm not sure what's similar between that crash log and the one attached to this issue. It looks to be another instance of the particle spawning issue with Ice and Fire. I opened a PR on their GitHub [here](https://github.com/Alex-the-666/Ice_and_Fire/pull/1569) approximately two weeks ago to fix the issue but there has been radio silence since. You will simply have to wait for an update from their team.

**Comment by jellysquid3** [comment]
This issue (being the one first reported by the original poster) has since been resolved by EvilCraft in commit https://github.com/CyclopsMC/EvilCraft/commit/b4586de5ba9d9997dca300165497002313e3e18e.
