### ISSUE TITLE
mod needing spongeforge 3639

### ISSUE THREAD

**Issue by HybridAvenger69** [jellysquid3/Phosphor#8]
I updating Enigmatica 2 to 1.65a
its telling me that i dont have 3639 or newer telling me basically that i have a older version
i did try putting it in there, still didnt work this is latest crash log from my server
https://pastebin.com/0J1BY8P2

**Comment by jellysquid3** [comment]
This is not an issue with Phosphor. Your log file indicates that you have an old version of SpongeForge installed. Please remove SpongeForge from your `mods` directory and install the latest version of SpongeForge from [here](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2).

**Comment by phit** [comment]
any reason you are depending on a newer sponge version directly?

**Comment by jellysquid3** [comment]
The minimum version requirement was set due to SpongeForge making breaking changes to `World#setBlockState` which broke Phosphor's mixins. It is possible that we could implement two sets of mixins for various Sponge versions, but it would introduce a maintenance burden and it's not entirely clear to me how we could easily detect the Sponge version during the coremod initialization phase. 

I went with the route of choosing to only support recent versions because it would mean being able to ship a version today that would continue working for the foreseeable future on SpongeForge without requiring updates to the mod.

**Comment by HybridAvenger69** [comment]
in the file it says it requires spongeforge@[1.12.2-2768-7.1.6-RC3639 i tried newer versions, but i eneded up disabling that mod
