### ISSUE TITLE
Setting `enable_illegal_thread_access_warnings` to `false` does nothing.

### ISSUE THREAD

**Issue by Syphenion** [jellysquid3/Phosphor#9]
I still get warnings about Pixelmon even though I have set `enable_illegal_thread_access_warnings` to `false`. 
Using phosphor-1.12.2-0.2.2+build43-universal.jar.

**Comment by jellysquid3** [comment]
This was a rather strange issue. It seems that the configuration file was being loaded correctly but some code couldn't see the non-default values assigned to configuration values due to an issue with either Gson or the Java VM itself. Removing the `final` attributes from our configuration entries has resolved the issue.

2b4640e97f8248d7fe7478bcd55cdd4019a4d2f9 fixes this issue. I will close the issue once release 0.2.3 is made on Curseforge.

**Comment by jellysquid3** [comment]
[The latest release of Phosphor (version 0.2.3) has been published to Curseforge.](https://minecraft.curseforge.com/projects/phosphor/files/2706848)
